apiVersion: v1
kind: ConfigMap
metadata:
   name: #{k8.CONFIG_MAP_NAME}# 
   namespace: #{k8.APP_NAMESPACE}#
data:
   appsettings.json: |-
     {
        "SqlConnectionString": "#{App.SqlConnectionString}#" ,
        "AppId": "#{App.AppId}#",
        "AppSecret": "#{App.AppSecret}#",
        "RejectCancellationRequestCron": "#{App.RejectCancellationRequestCron}#",
        "DataBaseCrediNetCredits": "#{App.DataBaseCrediNetCredits}#",
        "DefaultCountry": "#{App.DefaultCountry}#" ,
        "ParametersCacheMilliseconds": #{App.ParametersCacheMilliseconds}#,
        "ServiceBusConnectionStringRequest": "#{App.ServiceBusConnectionStringRequest}#",
        "EventsTopicName": "#{App.EventsTopicName}#" ,
        "StorageAccount": "#{App.StorageAccount}#" ,
        "CultureInfo": "#{App.CultureInfo}#" ,
        "DomainName": "#{App.DomainName}#",
        "MessagingSqlConnectionString": "#{App.MessagingSqlConnectionString}#",
        "MessagingDatabaseName": "#{App.MessagingDatabaseName}#",
        "StoreAllowPromissoryNoteSignatureDefault": #{App.StoreAllowPromissoryNoteSignatureDefault}#,
        "UserToRejectCancellationRequests": "#{App.UserToRejectCancellationRequests}#",
        "UserIdToRejectCancellationRequests": "#{App.UserIdToRejectCancellationRequests}#",
        "Serilog": {
            "Using": [ "Serilog.Sinks.Console",  "Serilog.Sinks.Elasticsearch" ],
            "MinimumLevel": "#{App.SerilogMinimumLevel}#",
            "WriteTo": [
              {
                "Name": "Console"
              },
              {
                "Name": "Elasticsearch",
                "Args": {
                  "NodeUris": "#{App.Serilog.Elasticsearch.NodeUris}#",
                  "IndexFormat": "#{App.Serilog.Elasticsearch.IndexFormat}#"
                }
              }
            ],
            "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId", "WithExceptionDetails" ],
            "Properties": {
                "Application": "#{App.SerilogApplication}#"
            }
        }
     }   